Created Empire category for commands, and added Start, Reset, and Empire commands.
RyanLandDev/EmpireBot pull request #10
Opened 2021-08-12 13:05 UTC by General-Mudkip

2021-08-12 17:07 UTC, RyanLandDev requested changes

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/EmpireCommand.java
> +        if (document == null) {
Putting this in every gameplay related command would be inefficient. This is why we have a RequireProfileCheck. Instead, after .category() put .requiresProfile() and remove this check

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/EmpireCommand.java
> +                    "\n**Created:** ", String.valueOf(document.created),
Instead of this, maybe make the UserDocument getters return non-primitive values (`Integer` instead of `int`) so you can use .toString() instead of String.valueOf()

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/EmpireCommand.java
> +                    .addField("",
Use PresetBuilder

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/bot/command/help/Category.java
> +    EMPIRE("Empire","Commands that concern the actual game.","🎮");
There will be a lot of gameplay commands, so wouldn't it be better if we called this category "Profile" like on the old bot?

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/ResetProfileCommand.java
> +        document.clear();
For the document you can instead use `event.getUserDocument()` and put `requiresProfile()` in the `getInfo()` method. Additionally, document.clear() method only clears this instance, not the actual remote database. Instead use DocumentCache#remove (I am going to make this method now..)

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/ResetProfileCommand.java
> +        event.reply("Reset").setEphemeral(true).queue();
We should make a confirmation box, perhaps with a code like in the old bot, however we gotta discuss this a bit more as the code does require message content access

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/StartCommand.java
> +            ).setEphemeral(true).queue();
We could make a system which makes PresetBuilders with the type ERROR be ephemeral by default

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/StartCommand.java
> +            newDocument.setCreated(new Date());
This does not actually make it work, you have to call the `update()` method.

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/sys/database/documents/impl/UserDocument.java
> +    public static final Date DEFAULT_DATE = new Date();
No need for a default date

2021-08-12 17:07 UTC, ryandev2 commented on src/main/java/net/ryanland/empire/sys/database/documents/impl/UserDocument.java
> +        return this.created;
This will not work; it should be reversed to the old: `getDate("created")`

2021-08-12 17:17 UTC, General-Mudkip commented on src/main/java/net/ryanland/empire/bot/command/help/Category.java
> +    EMPIRE("Empire","Commands that concern the actual game.","🎮");
I think "Profile" is a bit more confusing than "Empire" imo. What kind of gameplay commands would there be that don't apply to the category?

2021-08-12 17:19 UTC, RyanLandDev commented on src/main/java/net/ryanland/empire/bot/command/help/Category.java
> +    EMPIRE("Empire","Commands that concern the actual game.","🎮");
https://github.com/RyanLandDev/empire/tree/master/src/main/java/net/ryanland/empire/bot/commands/impl
I can agree that Profile is not the best name but its certainly better than Empire imo as Empire is literally the entire bot or every gameplay thing

2021-08-12 17:24 UTC, General-Mudkip commented on src/main/java/net/ryanland/empire/bot/command/help/Category.java
> +    EMPIRE("Empire","Commands that concern the actual game.","🎮");
Changed

2021-08-12 17:30 UTC, bencered commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/ResetProfileCommand.java
> +        event.reply("Reset").setEphemeral(true).queue();
Yep, this was just a temporary solution

2021-08-12 21:24 UTC, RyanLandDev commented on src/main/java/net/ryanland/empire/bot/command/impl/empire/ResetProfileCommand.java
> +        DocumentCache.delete(document.getId(), UserDocument.class);
Can't you remove line 28 and just use event.getUser().getId() ?

2021-08-13 12:39 UTC, RyanLandDev approved these changes

2021-08-13 12:39 UTC, merged